### ISSUE TITLE
Not testing I/O (yet)

### ISSUE THREAD

**Issue by pensierinmusica** [mroth/phoenix-showdown#11]
Hi, I think this comparison work is amazing and very much needed, thanks for putting it together!

I even wrote a [question on Quora](http://www.quora.com/Is-there-any-performance-comparison-between-web-back-end-server-frameworks) sometime ago about this. Take a look at the question details.

It would be interesting to include some I/O processes in the test, as they're present in basically any real web app. Otherwise I think the results might be quite misleading. Imagine basic disk reading, or DB CURD operations. The DB side of things could be standardized using always the same technology (e.g. MYSQL / MongoDB).

Imho, the entire point of using aync technology is that it's non-blocking. Otherwise we'd all stick to sync code. Unfortunately this does not have any relevance in the current test.

Thoughts?

**Comment by josevalim** [comment]
Actually, the tests are very IO bound because the server is doing so little CPU use that the client/server IO is going to be the bottleneck. That's at least the case when I benchmarked Phoenix and Plug. CPU usage does not max out, we just can't push more load to it. Maybe it does max CPU usage in other languages but that just goes to show other languages will use more CPU even on the simplest of tasks.

In any case, the current benchmark are very specific about what they are. Sure, you could benchmark the DB interaction, but that would be another set of benchmarks, not this one.

Finally, your comment about async technology is a bit off. All languages currently benchmarked do not block on IO. Even Ruby if you are using threads.
